train_model: True
epochs: 50
file_name: "fashion_mnist"

channels: 64
channel_multiplier: [1, 2, 3]
block_depth: 2
emb_size: 512
num_classes: 12
attention_levels: [0, 1, 0]
embedding_dims: 32
embedding_max_frequency: 1000.0

precomputed_embedding: False
save_in_drive: False

batch_size: 64
num_imgs: 64
row: 8
learning_rate: 0.0003

class_guidance: 1
MODEL_NAME: "model_test"
from_scratch: True
data_dir: "/content/diffusion_model_aesthetic_keras"